version: '3'

services:
  php:
    build: 
      context: ./docker/php
    ports:
      - "9001:9000"
    volumes:
      - ./website/:/var/www/html/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    ports:
      - "80:80"
    volumes:
      - ./website/:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root